2023年度学年歴追加
twin-te/school-calendar-service pull request #8
Opened 2023-03-27 16:52 UTC by SIY1121

学年暦ページとpdfを見ながら手動で作っているので、打ち間違い等無いかチェックお願いします。
https://www.tsukuba.ac.jp/campuslife/calendar-school/2023.html

2023-03-31 14:49 UTC, takonasu requested changes
お疲れ様です！
修正点コメントしたので確認お願いします！

2023-03-31 14:49 UTC, takonasu commented on school-calendar/events2023.json
> +        "type": "Other",
授業は休講なので `Holiday`
（ちなみに去年のjsonもHoliday）

2023-03-31 14:49 UTC, takonasu commented on school-calendar/events2023.json
> +        "type": "Other",
`Holiday`

2023-03-31 14:49 UTC, takonasu commented on school-calendar/events2023.json
> +        "type": "Other",
`Holiday`

2023-03-31 14:49 UTC, takonasu commented on school-calendar/events2023.json
> +        "type": "Other",
`Holiday`

2023-03-31 14:49 UTC, takonasu commented on school-calendar/events2023.json
> +        "type": "Other",
`Holiday`

2023-03-31 14:49 UTC, takonasu commented on school-calendar/events2023.json
> +        "type": "Other",
`Holiday`

2023-03-31 14:49 UTC, takonasu commented on school-calendar/events2023.json
> +        "description": "開学記念日"
ここがなぜ休みなのかが不明。
PDFでは夏休みは9/30までだが授業開始は10/3からとなっている。
理由が不明なので「臨時休業」としておいたほうがよさそう

2023-03-31 14:49 UTC, takonasu commented on school-calendar/events2023.json
> +        "type": "Other",
授業は休講なので `Holiday`
2022年度は`Other`になっていましたがこれはミスですね・・・

2023-03-31 14:49 UTC, takonasu commented on school-calendar/events2023.json
> +        "date": "2024-02-14",
`2024-02-14` はtypeがExamとSubstituteDayで重複登録されてるけど、SubstituteDayが優先されたほうが良い。

実装側でSubstituteDayは優先されるようになってますか？
（なってるならこれで大丈夫）

2023-03-31 14:49 UTC, takonasu commented on school-calendar/events2023.json
> +    {
去年は前期試験日程も入れていたので一応。
PDF的にはこれで会ってるんだけど、これ日曜日と月曜日なんだけどあってるんかね・・・
```   
    {
        "date": "2024-02-25",
        "type": "Other",
        "description": "個別学力検査等前期日程"
    },
    {
        "date": "2024-02-26",
        "type": "Other",
        "description": "個別学力検査等前期日程"
    },
```

2023-03-31 14:49 UTC, takonasu commented on school-calendar/events2023.json
> +        "date": "2022-11-05",
`2023-11-05`

2023-03-31 14:49 UTC, takonasu commented on school-calendar/events2023.json
> +        "date": "2022-11-06",
`2023-11-06`

2023-04-01 13:20 UTC, SIY1121 commented on school-calendar/events2023.json
> +        "type": "Other",
春Aの期限を4/13からにしたからHolidayである必要はないんだけど、どっちが良いかね？
春A期間を4/5からにしたらHolidayじゃないとウィジットに授業が出るっていう感じなんだけど

2023-04-01 13:22 UTC, SIY1121 commented on school-calendar/events2023.json
> +        "type": "Other",
この日って結局授業なかったんだっけ？（覚えてない）

2023-04-01 13:24 UTC, SIY1121 commented on school-calendar/events2023.json
> +        "date": "2024-02-14",
eventは1日に複数入ることもありうる想定なので両方登録されます

2023-04-01 13:24 UTC, SIY1121 commented on school-calendar/events2023.json
> +        "date": "2022-11-05",
修正しました

2023-04-01 13:24 UTC, SIY1121 commented on school-calendar/events2023.json
> +        "date": "2022-11-06",
修正しました

2023-04-01 13:25 UTC, SIY1121 commented on school-calendar/events2023.json
> +        "description": "開学記念日"
一応pdfの注5には、記念日イベントの関係で休みって書いてあるね

2023-04-01 13:27 UTC, SIY1121 commented on school-calendar/events2023.json
> +    {
追記しました

2023-04-01 13:28 UTC, SIY1121 commented on school-calendar/events2023.json
> +        "type": "Other",
ウィジットの表示上の違いは、春Aの上で休日なのか、春Aではないので何も出ないかの違い

2023-04-01 13:29 UTC, SIY1121 commented on school-calendar/events2023.json
> +        "type": "Other",
あ、あとiosだと休日の通知だしてたっけ
4/5~4/12まで休日の通知が飛ぶかどうかってのもある？

2023-04-02 02:28 UTC, takonasu commented on school-calendar/events2023.json
> +        "type": "Other",
あーなるほど
https://github.com/twin-te/twinte-ios/blob/b0e1206e9fe4f9bc6dea6cfe7fd76d07086a354b/Twinte/ScheduleNotification.swift#L51
的には、iOSはHolidayで通知をだすね。
結局通知を出すか出さないかの違いか～
新入生にとっては通知があるとうれしい気がするのと、B2以上の人にとっても授業あるかわからなくなるから通知があるといいかも

2023-04-02 02:29 UTC, takonasu commented on school-calendar/events2023.json
> +        "description": "開学記念日"
注5見落としてた、ありがとう！
開学記念日は10/1で10/2は開学記念日ではないので、「臨時休業」にしよう！

2023-04-02 02:31 UTC, takonasu commented on school-calendar/events2023.json
> +        "type": "Other",
PDFの色を見る感じ、塗りつぶされてないので授業日ではないかと！
あと、推薦試験準備もかねて休講なのかと思う

2023-04-02 02:32 UTC, takonasu commented on school-calendar/events2023.json
> +        "type": "Other",
あと、４月のこの時期に通知を仕込むことで通知機能があるよっていう宣伝にもなるかも

2023-04-02 04:30 UTC, HosokawaR commented on school-calendar/module2023.json
> +[
[相談]

[学年暦ページ](https://www.tsukuba.ac.jp/campuslife/calendar-school/2023.html)には

> 春季休業 筑波キャンパス 4月1日（土） ～ 4月4日（火）

とありますが、以下のように反映したほうがいいでしょうか？

```suggestion
[
  {
      "year": 2023,
      "module": "SpringVacation",
      "start": "2023-04-01",
      "end": "2023-01-04"
  },
```

2023-04-02 04:33 UTC, HosokawaR commented on school-calendar/events2023.json
> +  },
[相談]

[PDF](https://www.tsukuba.ac.jp/campuslife/calendar-school/pdf/2023-undergrad-grad-tsukuba.pdf) には

> 新入生オリエンテーション4.5-4.7

とありますが、同じように 2023-04-05,  2023-04-06 にも`"新入生オリエンテーション"`が登録されていたほうがいいのですかね？

2023-04-02 04:53 UTC, HosokawaR commented on school-calendar/events2023.json
> +  },
[MEMO]

[PDF](https://www.tsukuba.ac.jp/campuslife/calendar-school/pdf/2023-undergrad-grad-tsukuba.pdf) には

> 学群編入学試験7.8-7.9予定

とあるが、これは対象者が限られそうなので、現行通りなくてもいいと感じた

2023-04-02 05:18 UTC, HosokawaR commented on school-calendar/events2023.json
> +  },
[相談]

PDF には 

> 個別学力検査等後期日程3.12

とあるので、「個別学力検査等**前**期日程」があるなら「個別学力検査等**後**期日程」もあってもいいかなと少し思いました。

2023-04-02 05:29 UTC, SIY1121 commented on school-calendar/events2023.json
> +        "type": "Other",
1週間ずっと通知されるの邪魔かなと思ったけど、早い段階で通知の宣伝するのもまあありかも。
通知出す方針で良いですか？

2023-04-02 05:29 UTC, SIY1121 commented on school-calendar/events2023.json
> +        "description": "開学記念日"
修正done

2023-04-02 05:29 UTC, SIY1121 commented on school-calendar/events2023.json
> +        "type": "Other",
修正done

2023-04-02 05:30 UTC, SIY1121 commented on school-calendar/module2023.json
> +[
dbスキーマの問題で2023年度にSpringVacationが2つ入れられないので入れてないです、、、
（設定しなくても実害は無い）
できたらどこかのタイミングで直した方が良いかも

2023-04-02 05:30 UTC, SIY1121 commented on school-calendar/events2023.json
> +  },
1日にイベント複数入れてもウィジットに表示できるイベントは一つなのと、どちらのイベントを表示するか制御ができないので1つで良いかって感じです。
ウィジット以外でイベントを一覧で表示するようなものを計画してるなら、表示優先度みたいな制御データが必要になるかも。

2023-04-02 05:32 UTC, SIY1121 commented on school-calendar/events2023.json
> +  },
確かに、追加しました

2023-04-02 05:35 UTC, HosokawaR commented on school-calendar/module2023.json
> +[
了解です！
正直なくても実害はないのでこのままでいいと思いました。

2023-04-02 05:35 UTC, HosokawaR commented on school-calendar/events2023.json
> +  },
なるほどー
とりあえず「新入生オリエンテーション」の表示優先度のほうが低いので、一旦このままで良いと思いました！

2023-04-02 14:57 UTC, takonasu commented on school-calendar/events2023.json
> +        "type": "Other",
いったん通知出す方向でお願いします 🙏

2023-04-03 04:22 UTC, SIY1121 commented on school-calendar/events2023.json
> +        "type": "Other",
更新しました

2023-04-03 04:27 UTC, takonasu approved these changes
ありがとう！お疲れ様です！

2023-04-03 05:02 UTC, merged